/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.esd;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        LerArquivoInverso classUnderTest = new LerArquivoInverso();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
